# Generated by Django 4.2.6 on 2023-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('condition_type', models.CharField(choices=[('json', 'JSON-валидный'), ('text', 'Есть определенный текст'), ('status_code', 'Статус 200')], max_length=20, verbose_name='Условие')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст для поиска')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время проверки')),
                ('is_result', models.BooleanField(blank=True, null=True, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
